#ifndef GEOMETRY_H
#define GEOMETRY_H

const int NUMBER_OF_TELESCOPES = 14;
const int NUMBER_OF_STRIPS = 32;
const int CSIS_PER_TELESCOPE = 4;

const int TOTAL_CSIS = NUMBER_OF_TELESCOPES*CSIS_PER_TELESCOPE;

#endif
